name: SwifterSwiftUI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Tests
    runs-on: macos-latest
    strategy:
      matrix:
        xcode: ['/Applications/Xcode_11.3.app/Contents/Developer']
    env:
      PROJECT: SwifterSwiftUI.xcodeproj
      DERIVED_PATH: .build/derivedData
    steps:
    - uses: actions/checkout@v2
    - name: Swift Build
      run: swift build
    - name: Bundle Install
      run: bundle install
    - name: Tests
      run: |
        swift test --enable-code-coverage | XCPRETTY_JSON_FILE_OUTPUT="xcodebuild-ios.json" xcpretty -f `xcpretty-json-formatter`

